# Generated by Django 4.1 on 2023-05-12 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='img',
            field=models.ImageField(blank=True, default='media/default.jpg', null=True, upload_to='media/'),
        ),
    ]
