# Generated by Django 4.1 on 2023-05-12 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_commodity_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='img',
            field=models.ImageField(default='default.jpg', upload_to='media/'),
        ),
    ]
