# Generated by Django 4.1 on 2023-05-12 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_commodity_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='img',
            field=models.ImageField(default='default.png', upload_to='media'),
        ),
    ]
